import type { Lang } from "@/lib/i18n"

const pt: string[] = [
  "Revisar conceitos 24h após o aprendizado aumenta a retenção em até 90%.",
  "A prática de recuperação ativa (tentar responder sem consultar o material) é mais eficaz do que reler passivamente.",
  "Alternar entre diferentes temas clínicos durante os estudos melhora a retenção a longo prazo.",
  "Dormir bem após estudar consolida a memória tanto quanto o próprio estudo.",
  "Resolver questões antes de estudar a teoria ajuda o cérebro a identificar lacunas de conhecimento.",
  "Sessões curtas e frequentes de revisão são mais eficazes do que uma única sessão longa e cansativa.",
  "Explicar um conceito em voz alta, como se estivesse ensinando, fortalece a memória de longo prazo.",
  "Fazer pausas estratégicas a cada 50 minutos de estudo aumenta o foco e a produtividade.",
  "Simular a pressão de tempo da prova real treina o controle emocional para o dia da avaliação.",
  "Revisar seus erros é mais valioso para o aprendizado do que revisar o que você já acertou.",
  "Criar mapas mentais ajuda a conectar conceitos clínicos de diferentes especialidades.",
  "Ensinar um colega é uma das formas mais eficazes de fixar o conhecimento na memória.",
  "Estudar em grupo e se questionar mutuamente ajuda a identificar lacunas antes da prova.",
  "Refazer questões erradas após alguns dias consolida o aprendizado de forma duradoura.",
  "Organizar um cronograma realista evita a sobrecarga e melhora a constância nos estudos.",
  "Hidratar-se e se alimentar bem antes de estudar melhora significativamente o desempenho cognitivo.",
  "Estudar casos clínicos completos, do início ao fim, treina o raciocínio que a prova realmente cobra.",
  "Revisar o conteúdo pouco antes de dormir ajuda o cérebro a consolidar as informações durante o sono.",
  "Alternar entre teoria e prática (resumos e questões) fixa melhor o conhecimento do que estudar só teoria.",
  "Registrar suas dúvidas durante o estudo e revisá-las depois evita que elas se acumulem.",
  "Cada questão resolvida hoje é um passo mais perto da sua aprovação no parcial.",
  "A constância vale mais do que a intensidade — continue, um dia de cada vez.",
  "Todo estudante que já passou por um parcial difícil também se sentiu inseguro em algum momento. Continue estudando.",
  "Seu esforço de hoje é o médico que você será amanhã.",
  "Não é sobre ser perfeito, é sobre estar mais preparado do que ontem.",
  "A aprovação começa na disciplina de estudar mesmo nos dias difíceis.",
  "Você não precisa saber tudo hoje — precisa apenas continuar avançando.",
  "Cada erro identificado no estudo é uma chance a menos de errar na prova real.",
  "Confie no processo: repetição e prática constroem segurança clínica de verdade.",
  "Sua aprovação é construída questão por questão, resumo por resumo, dia após dia.",
  "Lembre-se do motivo que te trouxe até aqui — ele é maior do que o cansaço de hoje.",
  "Progresso nem sempre é visível, mas ele está acontecendo a cada sessão de estudo.",
  "Persista: seus futuros pacientes também precisam da sua dedicação e do seu cuidado.",
  "Comparar-se com quem já passou não ajuda — compare-se com você mesmo há um mês.",
  "Estudar com propósito claro rende mais do que estudar por obrigação.",
  "Cada simulado é um ensaio seguro para os erros que você não quer cometer na hora real.",
  "A ansiedade antes da prova diminui na mesma medida em que a prática aumenta.",
  "Pequenas metas diárias, cumpridas com constância, levam a grandes resultados no parcial.",
  "Descansar também faz parte do estudo — um cérebro exausto aprende menos.",
  "Sua trajetória até aqui já prova que você é capaz de chegar à aprovação.",
]

const es: string[] = [
  "Repasar conceptos 24h después de aprenderlos aumenta la retención hasta un 90%.",
  "La práctica de recuperación activa (intentar responder sin mirar el material) es más eficaz que releer pasivamente.",
  "Alternar entre distintos temas clínicos durante el estudio mejora la retención a largo plazo.",
  "Dormir bien después de estudiar consolida la memoria tanto como el propio estudio.",
  "Resolver preguntas antes de estudiar la teoría ayuda al cerebro a identificar vacíos de conocimiento.",
  "Sesiones cortas y frecuentes de repaso son más eficaces que una sola sesión larga y agotadora.",
  "Explicar un concepto en voz alta, como si estuvieras enseñando, fortalece la memoria a largo plazo.",
  "Hacer pausas estratégicas cada 50 minutos de estudio aumenta el foco y la productividad.",
  "Simular la presión de tiempo del examen real entrena el control emocional para el día de la evaluación.",
  "Repasar tus errores es más valioso para el aprendizaje que repasar lo que ya sabés.",
  "Crear mapas mentales ayuda a conectar conceptos clínicos de distintas especialidades.",
  "Enseñarle a un compañero es una de las formas más eficaces de fijar el conocimiento en la memoria.",
  "Estudiar en grupo y preguntarse mutuamente ayuda a identificar vacíos antes del examen.",
  "Rehacer preguntas que fallaste después de algunos días consolida el aprendizaje de forma duradera.",
  "Organizar un cronograma realista evita la sobrecarga y mejora la constancia en el estudio.",
  "Hidratarte y alimentarte bien antes de estudiar mejora significativamente el rendimiento cognitivo.",
  "Estudiar casos clínicos completos, de principio a fin, entrena el razonamiento que el examen realmente evalúa.",
  "Repasar el contenido poco antes de dormir ayuda al cerebro a consolidar la información durante el sueño.",
  "Alternar entre teoría y práctica (resúmenes y preguntas) fija mejor el conocimiento que estudiar solo teoría.",
  "Anotar tus dudas durante el estudio y repasarlas después evita que se acumulen.",
  "Cada pregunta resuelta hoy es un paso más cerca de tu aprobación en el parcial.",
  "La constancia vale más que la intensidad — seguí, un día a la vez.",
  "Todo estudiante que ya pasó por un parcial difícil también se sintió inseguro en algún momento. Seguí estudiando.",
  "Tu esfuerzo de hoy es el médico o la médica que serás mañana.",
  "No se trata de ser perfecto, se trata de estar más preparado que ayer.",
  "La aprobación empieza en la disciplina de estudiar incluso en los días difíciles.",
  "No necesitás saberlo todo hoy — solo necesitás seguir avanzando.",
  "Cada error identificado en el estudio es una oportunidad menos de fallar en el examen real.",
  "Confiá en el proceso: la repetición y la práctica construyen seguridad clínica de verdad.",
  "Tu aprobación se construye pregunta por pregunta, resumen por resumen, día tras día.",
  "Recordá el motivo que te trajo hasta acá — es más grande que el cansancio de hoy.",
  "El progreso no siempre es visible, pero está sucediendo en cada sesión de estudio.",
  "Persistí: tus futuros pacientes también necesitan tu dedicación y tu cuidado.",
  "Compararte con quien ya aprobó no ayuda — comparate con vos mismo/a de hace un mes.",
  "Estudiar con un propósito claro rinde más que estudiar por obligación.",
  "Cada simulacro es un ensayo seguro para los errores que no querés cometer en el momento real.",
  "La ansiedad antes del examen disminuye en la misma medida en que la práctica aumenta.",
  "Pequeñas metas diarias, cumplidas con constancia, llevan a grandes resultados en el parcial.",
  "Descansar también es parte del estudio — un cerebro agotado aprende menos.",
  "Tu trayectoria hasta acá ya demuestra que sos capaz de llegar a la aprobación.",
]

export const STUDY_TIPS_BY_LANG: Record<Lang, string[]> = { pt, es }
