export const STUDY_TIPS: string[] = [
  "Revisar conceitos 24h após o aprendizado aumenta a retenção em até 90%.",
  "A prática de recuperação ativa (tentar responder sem consultar o material) é mais eficaz do que reler passivamente.",
  "Alternar entre diferentes temas clínicos durante os estudos melhora a retenção a longo prazo.",
  "Dormir bem após estudar consolida a memória tanto quanto o próprio estudo.",
  "Resolver questões antes de estudar a teoria ajuda o cérebro a identificar lacunas de conhecimento.",
  "Sessões curtas e frequentes de revisão são mais eficazes do que uma única sessão longa e cansativa.",
  "Explicar um conceito em voz alta, como se estivesse ensinando, fortalece a memória de longo prazo.",
  "Fazer pausas estratégicas a cada 50 minutos de estudo aumenta o foco e a produtividade.",
  "Simular a pressão de tempo da prova real treina o controle emocional para o dia da avaliação.",
  "Revisar seus erros é mais valioso para o aprendizado do que revisar o que você já acertou.",
  "Criar mapas mentais ajuda a conectar conceitos clínicos de diferentes especialidades.",
  "Refazer questões erradas após alguns dias consolida o aprendizado de forma duradoura.",
  "Organizar um cronograma realista evita a sobrecarga e melhora a constância nos estudos.",
  "Hidratar-se e se alimentar bem antes de estudar melhora significativamente o desempenho cognitivo.",
  "Estudar casos clínicos completos, do início ao fim, treina o raciocínio que a prova realmente cobra.",
  "Revisar o conteúdo pouco antes de dormir ajuda o cérebro a consolidar as informações durante o sono.",
  "Alternar entre teoria e prática (resumos e simulados) fixa melhor o conhecimento do que estudar só teoria.",
  "Registrar suas dúvidas durante o estudo e revisá-las depois evita que elas se acumulem.",
  "Cada simulado resolvido hoje é um passo mais perto da sua aprovação.",
  "A constância vale mais do que a intensidade — continue, um dia de cada vez.",
  "Todo médico aprovado já se sentiu inseguro em algum momento. Continue treinando.",
  "Seu esforço de hoje é o médico que você será amanhã.",
  "Não é sobre ser perfeito, é sobre estar mais preparado do que ontem.",
  "A aprovação começa na disciplina de estudar mesmo nos dias difíceis.",
  "Você não precisa saber tudo hoje — precisa apenas continuar avançando.",
  "Cada erro identificado em um simulado é uma chance a menos de errar na prova real.",
  "Confie no processo: repetição e prática constroem segurança clínica de verdade.",
  "Sua aprovação é construída questão por questão, dia após dia.",
  "Lembre-se do motivo que te trouxe até aqui — ele é maior do que o cansaço de hoje.",
  "Progresso nem sempre é visível, mas ele está acontecendo a cada sessão de estudo.",
  "Comparar-se com quem já passou não ajuda — compare-se com você mesmo há um mês.",
  "Estudar com propósito claro rende mais do que estudar por obrigação.",
  "Cada simulado é um ensaio seguro para os erros que você não quer cometer na hora real.",
  "A ansiedade antes da prova diminui na mesma medida em que a prática aumenta.",
  "Pequenas metas diárias, cumpridas com constância, levam a grandes resultados.",
  "Descansar também faz parte do estudo — um cérebro exausto aprende menos.",
  "Sua trajetória até aqui já prova que você é capaz de chegar à aprovação.",
]
